@BASE_URL = http://localhost:5000
@ADMIN_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5MGVjYTFmLTY3OWItNGM4Mi04OTA1LTIyMGE1OGE0NzczYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NjkzNTYyMywiZXhwIjoxNzY3MDIyMDIzfQ.Clb3AWOsYNOfH5RmbbT9WVoim-gz8JtydkTR7Kx00zU
@RIDER_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0Njg0YzVmLWNlN2EtNGMwNi05NmM5LTg4NTJjMmYwNDIwMSIsInJvbGUiOiJyaWRlciIsImlhdCI6MTc2NjkzNTYwOSwiZXhwIjoxNzY3MDIyMDA5fQ.NAqwmQVKzAGmKakMcn0J7_aF02eYhD2Lel5uMvFAioA
@DRIVER_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZDUyNGVmLWM2M2YtNGRmZS04N2UzLTZmNzYzMzM1NTU0NSIsInJvbGUiOiJkcml2ZXIiLCJpYXQiOjE3NjY5MzU1ODAsImV4cCI6MTc2NzAyMTk4MH0.cRbWUPmsL8Kpf5-jjsmdf0vBh68yQMtzyWn0IkaCIT8
@adminID= 390eca1f-679b-4c82-8905-220a58a4773a
@riderId = d4684c5f-ce7a-4c06-96c9-8852c2f04201
@driverId = 4ed524ef-c63f-4dfe-87e3-6f7633355545
@rideId = ride-uuid
@reviewId = review-uuid
# ADMIN CREATE REVIEW (EMERGENCY)
POST {{BASE_URL}}/api/admin/reviews
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "rideId": "{{rideId}}",
  "reviewerId": "{{riderId}}",
  "revieweeId": "{{driverId}}",
  "rating": { "stars": 5 },
  "taps": [
    { "key": "safe_driving", "category": "positive", "pointValue": 3 }
  ],
  "reason": "User app crashed during submission"
}

###


### ADMIN GET REVIEW
GET http://localhost:3000/api/admin/reviews/{{reviewId}}
Authorization: Bearer {{ADMIN_TOKEN}}


###

# ADMIN UPDATE REVIEW
PUT {{BASE_URL}}/api/admin/reviews/{{reviewId}}
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "stars": 4
}

###

# ADMIN FLAG REVIEW
POST {{BASE_URL}}/api/admin/reviews/{{reviewId}}/flag
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "reason": "Suspicious behavior"
}

###

# ADMIN DELETE REVIEW
DELETE {{BASE_URL}}/api/admin/reviews/{{reviewId}}
Authorization: Bearer {{ADMIN_TOKEN}}

###