### REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "rider@sg.com",
  "password": "rider123",
  "role": "rider",
  "first_name": "Sangit",
  "last_name": "Pokhrel"
}

###

# LOGIN Rider
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "driver1@gmail.com",
  "password": "123"
}


###

# LOGIN Driver
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "driver@sg.com",
  "password": "driver123"
}

###

# LOGIN Admin
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@sg.com",
  "password": "driver123"
}


###