@BASE_URL = http://localhost:5000
@ADMIN_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5MGVjYTFmLTY3OWItNGM4Mi04OTA1LTIyMGE1OGE0NzczYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NjkzNTYyMywiZXhwIjoxNzY3MDIyMDIzfQ.Clb3AWOsYNOfH5RmbbT9WVoim-gz8JtydkTR7Kx00zU
@RIDER_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ0Njg0YzVmLWNlN2EtNGMwNi05NmM5LTg4NTJjMmYwNDIwMSIsInJvbGUiOiJyaWRlciIsImlhdCI6MTc2NjkzNTYwOSwiZXhwIjoxNzY3MDIyMDA5fQ.NAqwmQVKzAGmKakMcn0J7_aF02eYhD2Lel5uMvFAioA
@DRIVER_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRlZDUyNGVmLWM2M2YtNGRmZS04N2UzLTZmNzYzMzM1NTU0NSIsInJvbGUiOiJkcml2ZXIiLCJpYXQiOjE3NjY5MzU1ODAsImV4cCI6MTc2NzAyMTk4MH0.cRbWUPmsL8Kpf5-jjsmdf0vBh68yQMtzyWn0IkaCIT8
@adminID= 390eca1f-679b-4c82-8905-220a58a4773a
@riderId = d4684c5f-ce7a-4c06-96c9-8852c2f04201
@driverId = 4ed524ef-c63f-4dfe-87e3-6f7633355545
@rideId = 09de7eaf-4929-405b-bd17-4e7450ec87b1
@reviewId = review-uuid
###

# ADMIN CREATE RIDE
POST {{BASE_URL}}/api/admin/rides
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "rider_id": "{{riderId}}",
  "driver_id": "{{driverId}}",
  "status": "created"
}


###

# USER START RIDE
POST {{BASE_URL}}/api/rides/{{rideId}}/start
Authorization: Bearer {{RIDER_TOKEN}}

###

# USER COMPLETE RIDE
POST {{BASE_URL}}/api/rides/{{rideId}}/complete
Authorization: Bearer {{RIDER_TOKEN}}

###

# ADMIN FORCE COMPLETE RIDE
POST {{BASE_URL}}/api/admin/rides/{{rideId}}/force-complete
Authorization: Bearer {{ADMIN_TOKEN}}

###

# ADMIN UPDATE RIDE
PUT {{BASE_URL}}/api/admin/rides/{{rideId}}
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "status": "completed",
  "is_paid": true,
  "note": "Manually corrected by admin"
}

###

# ADMIN DELETE RIDE
DELETE {{BASE_URL}}/api/admin/rides/{{rideId}}
Authorization: Bearer {{ADMIN_TOKEN}}

###